/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDRESS 	0x40021000
#define PORTA_BASE_ADDRESS 	0x40010800

#define RCC_APB2ENR_OFFSET  0x18
#define GPIOA_CRH_OFFSET	0x04
#define GPIOA_ODR_OFFSET	0x0C

#define RCC_APB2ENR 		*((volatile uint32_t *)(RCC_BASE_ADDRESS + RCC_APB2ENR_OFFSET))
#define GPIOA_CRH 			*((volatile uint32_t *)(PORTA_BASE_ADDRESS + GPIOA_CRH_OFFSET))
#define GPIOA_ODR			*((volatile uint32_t *)(PORTA_BASE_ADDRESS + GPIOA_ODR_OFFSET))

typedef union{
	volatile uint32_t All_Ports;
	struct{
		volatile uint32_t RESERVED : 12;
		volatile uint32_t PIN13 : 1;
	}Bit_field;
}ODR_REG_t;

volatile ODR_REG_t *ODR = ((volatile ODR_REG_t *)(PORTA_BASE_ADDRESS + GPIOA_ODR_OFFSET));

void GPIO_Init(void){
	RCC_APB2ENR |= (1 << 2);

	GPIOA_CRH &= ~(0xF << 20);

	GPIOA_CRH |= (0x2 << 20);
}

void delay(volatile int count) {
    while(count--);
}

int main(void)
{

	GPIO_Init();

    /* Loop forever */
	while(1){
		// toggle bit 13 in PORTA
		GPIOA_ODR ^= (1 << 13);

//		 Option 2 :
//		ODR->All_Ports ^= (1 << 13);
//
//		 Option 3 :
//		ODR->Bit_field.PIN13 = 1;

		// delay
		delay(5000);
//
//		ODR->Bit_field.PIN13 = 0;
//
//		delay(5000);
	}

	return 0;
}
