/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "lcd.h"
#include "keypad.h"

#include "_7SEGMENT.h"


void clock_Init(){
	GPIOA_CLK_EN(); // IO port A clock enabled
	GPIOB_CLK_EN(); // IO port B clock enabled
}

lcd_t lcd1 = {
		.DataRegister = GPIOA,
		.ControlRegister = GPIOA,

		.DataPins[0].PinNum = GPIO_PIN0,
		.DataPins[0].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[0].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[0].PinState = GPIO_LOW,

		.DataPins[1].PinNum = GPIO_PIN1,
		.DataPins[1].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[1].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[1].PinState = GPIO_LOW,

		.DataPins[2].PinNum = GPIO_PIN2,
		.DataPins[2].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[2].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[2].PinState = GPIO_LOW,

		.DataPins[3].PinNum = GPIO_PIN3,
		.DataPins[3].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[3].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[3].PinState = GPIO_LOW,

		.DataPins[4].PinNum = GPIO_PIN4,
		.DataPins[4].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[4].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[4].PinState = GPIO_LOW,

		.DataPins[5].PinNum = GPIO_PIN5,
		.DataPins[5].PinMode = GPIO_OUTPUT_2MHZ,
		.DataPins[5].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[5].PinState = GPIO_LOW,

		.DataPins[6].PinNum = GPIO_PIN6,
		.DataPins[6].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[6].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[6].PinState = GPIO_LOW,

		.DataPins[7].PinNum = GPIO_PIN7,
		.DataPins[7].PinMode = GPIO_OUTPUT_10MHZ,
		.DataPins[7].PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.DataPins[7].PinState = GPIO_LOW,

		.RS.PinNum = GPIO_PIN8,
		.RS.PinMode = GPIO_OUTPUT_10MHZ,
		.RS.PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.RS.PinState = GPIO_LOW,

		.EN.PinNum = GPIO_PIN9,
		.EN.PinMode = GPIO_OUTPUT_10MHZ,
		.EN.PinCNF = GPIO_CNF_PUSH_PULL_OUTPUT,
		.EN.PinState = GPIO_LOW,
};


uint8 prev_key = '\0';
uint8 current_key;

int main(void)
{
	// Initializing the clock
	clock_Init();

	// Initializing the LCD
	lcd_initialize(&lcd1);

	// Initializing the 7-segment
	_7_segment_init();

	lcd_send_string_pos(&lcd1, "Hello World !", 1, 1);
	lcd_send_string_pos(&lcd1, "Mohamed Elsayed !", 2, 1);
	delay_ms(30);
	lcd_send_command(&lcd1, _LCD_CLEAR);

	// Variable to check pressed key of Keypad
	uint8_t pressed_key;

	// Array to store of 7 segments shapes
	uint8_t seg_Numbers[] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};

	// Array to store Numbers from 1 >>> 9 to be displayed on LCD
	uint8_t LCD_Numbers[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};

	// Loop to display the same number to LCD and 7-SEGMENT
	for (uint8_t i = 0; i < 11; i++)
	{
		// Display current number on the 7 segment
		MCAL_GPIO_WritePort(GPIOB, seg_Numbers[i] << 9);
		// We shifted by 9 as we used the First 9 Ports for Keypad and started connecting 7 segment from PB10

		// Display current number on the LCD
		lcd_send_char_data(&lcd1, LCD_Numbers[i]);
		// Delay to be able to see the change in numbers
		delay_ms(100);  // delay
	}

	// Clear screen after displaying Numbers
	lcd_send_command(&lcd1, _LCD_CLEAR);

	// Initializing the Keypad
	Keypad_init();

	lcd_send_string(&lcd1, "Keypad is ready!");
	delay_ms(30);
	lcd_send_command(&lcd1, _LCD_CLEAR);

	while(1)
	{
		pressed_key = Keypad_getkey();

		switch(pressed_key)
		{
			case 'A':
				break;

			case '?':
				lcd_send_command(&lcd1, _LCD_CLEAR);
				break;

			default:
				lcd_send_char_data(&lcd1, pressed_key);
				break;
		}
	}
}



